// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetStats():Promise<main.TransferStats>;

export function Receive():Promise<void>;

export function RestartReceive():Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function Send(arg1:string):Promise<void>;
