// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function Receive() {
  return window['go']['main']['App']['Receive']();
}

export function RestartReceive() {
  return window['go']['main']['App']['RestartReceive']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
